<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OsrStudio</RootNamespace>
    <AssemblyName>osr-cli</AssemblyName>
    <TargetFramework>net472</TargetFramework>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <UseAppConfigForCompiler>true</UseAppConfigForCompiler>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>..\OsrStudio\Images\OsrStudio.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="CopyAppConfig" AfterTargets="Build">
    <Copy SourceFiles="App.config" DestinationFiles="$(OutputPath)$(AssemblyName).exe.config" />
  </Target>
  <ItemGroup>
    <ProjectReference Include="..\\OsrStudio.Base\\OsrStudio.Base.csproj" />
    <ProjectReference Include="..\\OsrStudio.Core\\OsrStudio.Core.csproj" />
    <ProjectReference Include="..\\OsrStudio.Fakes\\OsrStudio.Fakes.csproj" />
    <ProjectReference Include="..\\OsrStudio.FFmpeg\\OsrStudio.FFmpeg.csproj" />
    <ProjectReference Include="..\\OsrStudio.Loc\\OsrStudio.Loc.csproj" />
    <ProjectReference Include="..\\OsrStudio.MouseKeyHook\\OsrStudio.MouseKeyHook.csproj" />
    <ProjectReference Include="..\\OsrStudio.SharpAvi\\OsrStudio.SharpAvi.csproj" />
    <ProjectReference Include="..\Screna\Screna.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\OsrStudio\Images\OsrStudio.ico">
      <Link>OsrStudio.ico</Link>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.2.1" />
  </ItemGroup>
  <Import Project="../PostBuild.targets" />
</Project>
